apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-album-web
  name: cloud-album-web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: cloud-album-web
  strategy: {}
  template:
    metadata:
      labels:
        app: cloud-album-web
    spec:
      serviceAccountName: ghcr
      containers:
      - image: ghcr.io/0kate/cloud-album-web:latest
        name: cloud-album-web
        resources: {}
status: {}
