apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-album-web
  name: cloud-album-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cloud-album-web
status:
  loadBalancer: {}
